# Generated by Django 4.1.2 on 2022-11-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.IntegerField()),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_salry', models.FloatField(max_length=50)),
                ('emp_adress', models.CharField(max_length=150)),
            ],
        ),
    ]
